import dotenv from 'dotenv';
import GeminiService from './services/content-engine/GeminiService.js';
import ContentGenerator from './services/content-engine/ContentGenerator.js';
import ImageGenerator from './services/render-engine/ImageGenerator.js';

dotenv.config();

async function runPipeline() {
    console.log("🚀 Starting Daily Instagram Automation Pipeline...");

    const aiService = new GeminiService();
    const contentEngine = new ContentGenerator(aiService);
    const renderEngine = new ImageGenerator();

    const topic = "Microservices Architecture vs Monoliths";

    try {
        console.log("\n[STAGE 1] Triggering Content Engine...");
        const aiData = await contentEngine.createDailyPost(topic);

        // Extract the dynamic tag generated by the AI and format it
        const dynamicTag = aiData.theme_tag.toUpperCase();

        console.log("\n[STAGE 2] Triggering Render Engine...");

        // 1. Render the Title Slide
        await renderEngine.createSlide(
            aiData.post_title,
            "Swipe to explore the architecture ➔",
            0,
            dynamicTag,
            false
        );

        // 2. Render the Dynamic Educational Slides
        for (let i = 0; i < aiData.slides.length; i++) {
            const slide = aiData.slides[i];
            await renderEngine.createSlide(
                slide.slide_title,
                slide.bullet_points,
                i + 1,
                dynamicTag, // Passing the AI's tag contextually to every slide
                false
            );
        }

        // 3. Render the Call to Action Slide
        await renderEngine.createSlide(
            "Want the Full Implementation Guide?",
            `Comment the word **${aiData.trigger_word}** below and I will instantly DM you the architecture diagrams and code examples.`,
            aiData.slides.length + 1,
            "FREE GUIDE",
            true
        );

        console.log("\n✅ Pipeline Complete! Check the services/render-engine/output folder.");

    } catch (error) {
        console.error("\n❌ Pipeline Failed:", error.message);
    }
}

runPipeline();